#!/bin/bash

sudo apt update -y

sleep 2

sudo apt install openjdk-11-jdk -y
sleep 2
sudo apt install maven -y
sleep 2
sudo wget -O /usr/share/keyrings/jenkins-keyring.asc \
    https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
sleep 3

echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
    https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
    /etc/apt/sources.list.d/jenkins.list > /dev/null

sudo apt-get update
sleep 2

sudo apt-get install jenkins -y

